#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.12.3

pipelines:
  default:
      - step:
          name: Build 
          caches:
            - pip
          script:
            - echo "Starting build process"
            - pip install --upgrade pip
            - pip install -r sabpaisa_pro/requirements.txt
     