image: python:3.12.3

pipelines:
  default:
    - step:
        name: Build artifact
        script:
          - pwd
          - ls -al
          - mkdir artifact
          - echo "Starting build process"
          - pip install --upgrade pip
          - pip install -r sabpaisa_pro/requirements.txt
          - echo "Pipelines is awesome!" 
        artifacts:
          - artifact/*
    - step:
        name: Deploy to S3
        deployment: Staging
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'ap-south-1'
              S3_BUCKET: 'protal-sabpaisa-fend '
              LOCAL_PATH: 'artifact'