# Generated by Django 5.0.6 on 2024-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0018_alter_transactiondetail_chargeback_request_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyushUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='alert_flag',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='auth_code',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='bank_message',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='bank_txn_id',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='enquiry_counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='fee_forward',
            field=models.CharField(default='NA', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='gst_rate_type',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='is_settled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='payment_mode',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='pg_name',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='pg_pay_mode',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='pg_response_code',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='pg_txn_id',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='resp_msg',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_by',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_remarks',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_status',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_utr',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='trans_complete_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='txn_id',
            field=models.CharField(default=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='udf19',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
