version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: spreportportal
      MYSQL_USER: root
      MYSQL_PASSWORD: Tyagi@2588
      MYSQL_ROOT_PASSWORD: Tyagi@2588
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3307"

  web:
    depends_on:
      -  db
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    
    environment:
      - DB_HOST=db
      - DB_NAME=spreportportal
      - DB_USER=root
      - DB_PASSWORD=Tyagi@2588
      - DB_PORT=3307

volumes:
  mysql_data:
