# Generated by Django 5.0.6 on 2024-06-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='challan_no',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
