# Generated by Django 5.0.6 on 2024-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0002_alter_transactiondetail_challan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='refund_message',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
