# Generated by Django 5.0.6 on 2024-06-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0005_alter_transactiondetail_vpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='vpa_remarks',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
