# Generated by Django 5.0.6 on 2024-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0006_alter_transactiondetail_vpa_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='charge_back_status',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
