# Generated by Django 5.0.6 on 2024-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0007_alter_transactiondetail_charge_back_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='trans_flag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
