# Generated by Django 5.0.6 on 2024-06-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0008_alter_transactiondetail_trans_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='udf20',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
