# Generated by Django 5.0.6 on 2024-06-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0009_alter_transactiondetail_udf20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='donation_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
