# Generated by Django 5.0.6 on 2024-06-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0010_alter_transactiondetail_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='card_brand',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
