# Generated by Django 5.0.6 on 2024-06-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0011_alter_transactiondetail_card_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='device_name',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
    ]
