# Generated by Django 5.0.6 on 2024-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0012_alter_transactiondetail_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='payer_confirmation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
