# Generated by Django 5.0.6 on 2024-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0013_alter_transactiondetail_payer_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='sent_notification_payer_confirmation_url',
            field=models.CharField(default='NA', max_length=500, null=True),
        ),
    ]
