# Generated by Django 5.0.6 on 2024-06-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0014_alter_transactiondetail_sent_notification_payer_confirmation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='bank_errorcode',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='charge_back_debit_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='ep_conv_rate_type',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='is_charge_back',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='sabpaisa_errorcode',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='sp_conv_rate_type',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
    ]
