# Generated by Django 5.0.6 on 2024-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0015_alter_transactiondetail_bank_errorcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='payer_confirmation_respones',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
    ]
