# Generated by Django 5.0.6 on 2024-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0016_alter_transactiondetail_payer_confirmation_respones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='refund_request_from',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
    ]
