# Generated by Django 5.0.6 on 2024-06-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0017_alter_transactiondetail_refund_request_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='chargeback_request_from',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
    ]
