# Generated by Django 5.0.6 on 2024-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0019_alter_transactiondetail_udf19'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_bank_amount_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
