# Generated by Django 5.0.6 on 2024-06-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0020_alter_transactiondetail_settlement_bank_amount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_bank_amount_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
