# Generated by Django 5.0.6 on 2024-06-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0025_alter_transactiondetail_resp_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='is_settled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
