# Generated by Django 5.0.6 on 2024-06-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0026_alter_transactiondetail_is_settled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='bank_message',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
