# Generated by Django 5.0.6 on 2024-06-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0027_alter_transactiondetail_bank_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_by',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_remarks',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_status',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_utr',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
    ]
