# Generated by Django 5.0.6 on 2024-06-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0028_alter_transactiondetail_settlement_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='enquiry_counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
