# Generated by Django 5.0.6 on 2024-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0029_alter_transactiondetail_enquiry_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='settlement_bank_amount_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
