# Generated by Django 5.0.6 on 2024-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0032_alter_transactiondetail_settlement_bank_amount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='pg_txn_id',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
