# Generated by Django 5.0.6 on 2024-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0033_alter_transactiondetail_pg_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='alert_flag',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
