# Generated by Django 5.0.6 on 2024-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0034_alter_transactiondetail_alert_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='auth_code',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='bank_txn_id',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
