# Generated by Django 5.0.6 on 2024-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0035_alter_transactiondetail_auth_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='pg_response_code',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
