# Generated by Django 5.0.6 on 2024-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0036_alter_transactiondetail_pg_response_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='trans_complete_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
