# Generated by Django 5.0.6 on 2024-06-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0039_alter_transactiondetail_pg_pay_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='payment_mode',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
