# Generated by Django 5.0.6 on 2024-06-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0040_alter_transactiondetail_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='fee_forward',
            field=models.CharField(default='NA', max_length=5, null=True),
        ),
    ]
