# Generated by Django 5.0.6 on 2024-07-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabpaisa_app', '0043_ayushuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='txn_id',
            field=models.CharField(default=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
