# Use the official Python image from the Docker Hub
FROM python:3.12.3

# Set environment variables


# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt


# Copy the project code into the container
COPY . /app/
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

