version: '3'

services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - 172.17.0.2
    environment:
      DATABASE_NAME: spreportportal
      DATABASE_USER: root
      DATABASE_PASSWORD: Tyagi@2588
      DATABASE_HOST: 172.17.0.2
      DATABASE_PORT: 3306
    networks:
      - app-network