version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Tyagi@2588
      MYSQL_DATABASE: spreportportal
      MYSQL_USER: root
      MYSQL_PASSWORD: Tyagi@2588
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql.dockerfile
      - ./path/to/my.cnf:/etc/mysql/my.cnf

  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
