version: '3.8'

services:
  networks:
    app-network:
      web:
        build: .
        container_name: django_web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/app
        ports:
          - "8000:8000"
    
volumes:
  db_data:

