version: '3'

services:
  db:
    image: mysql:8.4.0
    container_name: project_name_mariadb
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${Tyagi@2588}
      MYSQL_DATABASE: ${spreportportal}
      MYSQL_USER: ${root}
      MYSQL_PASSWORD: ${Tyagi@2588}
    ports:
      - "3308:3306"

  backend:
    build: .
    container_name: project_name_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  data: