version: '3'
services:
   db:
     image: mysql:8.4.0
     container_name: project_name_mysql
     restart: always
     volumes:
       - data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: Tyagi@2588
       MYSQL_DATABASE: spreportportal
       MYSQL_USER: root
       MYSQL_PASSWORD: Tyagi@2588
     ports:
       - "3307:3307"
  
  backend:
    network_mode: bridge
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: project_name_backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    
volumes:
  data:
